//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargotruck.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cargotruck.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor felület.
        /// </summary>
        public static string Admin_page {
            get {
                return ResourceManager.GetString("Admin_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor felület.
        /// </summary>
        public static string Admin_title {
            get {
                return ResourceManager.GetString("Admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rossz felhasználónév vagy jelszó..
        /// </summary>
        public static string Bad_username {
            get {
                return ResourceManager.GetString("Bad_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autómárka.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakományos.
        /// </summary>
        public static string Cargo_man {
            get {
                return ResourceManager.GetString("Cargo_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakományok.
        /// </summary>
        public static string Cargoes {
            get {
                return ResourceManager.GetString("Cargoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megváltoztatása.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljesítve.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljesítés ideje.
        /// </summary>
        public static string Completion_time {
            get {
                return ResourceManager.GetString("Completion_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás költsége.
        /// </summary>
        public static string Cost_of_storage {
            get {
                return ResourceManager.GetString("Cost_of_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás létrehozása.
        /// </summary>
        public static string Create_tasks {
            get {
                return ResourceManager.GetString("Create_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni szeretnéd?.
        /// </summary>
        public static string Delete_ {
            get {
                return ResourceManager.GetString("Delete?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás törlése.
        /// </summary>
        public static string Delete_tasks {
            get {
                return ResourceManager.GetString("Delete_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr fizetése.
        /// </summary>
        public static string Driver_salary {
            get {
                return ResourceManager.GetString("Driver_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr költése.
        /// </summary>
        public static string Driver_spending {
            get {
                return ResourceManager.GetString("Driver_spending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kereset.
        /// </summary>
        public static string Earning {
            get {
                return ResourceManager.GetString("Earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosít.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil szerkesztése.
        /// </summary>
        public static string Edit_profile {
            get {
                return ResourceManager.GetString("Edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás módosítása.
        /// </summary>
        public static string Edit_tasks {
            get {
                return ResourceManager.GetString("Edit_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres excel fájl!.
        /// </summary>
        public static string Empty_excel {
            get {
                return ResourceManager.GetString("Empty_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befejezés dátum.
        /// </summary>
        public static string Ending_date {
            get {
                return ResourceManager.GetString("Ending_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befejezés helye.
        /// </summary>
        public static string Ending_place {
            get {
                return ResourceManager.GetString("Ending_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az autómárka megadása kötelező!.
        /// </summary>
        public static string Error_brand {
            get {
                return ResourceManager.GetString("Error_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail megadása kötelezõ..
        /// </summary>
        public static string Error_email {
            get {
                return ResourceManager.GetString("Error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név megadása kötelezõ..
        /// </summary>
        public static string Error_full_name {
            get {
                return ResourceManager.GetString("Error_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jármű teherbírását kötelező megadni!.
        /// </summary>
        public static string Error_max_weight {
            get {
                return ResourceManager.GetString("Error_max_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt, kérlek próbáld meg később..
        /// </summary>
        public static string Error_page_text {
            get {
                return ResourceManager.GetString("Error_page_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner megadása kötelezõ..
        /// </summary>
        public static string Error_partner {
            get {
                return ResourceManager.GetString("Error_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megadása kötelezõ..
        /// </summary>
        public static string Error_password {
            get {
                return ResourceManager.GetString("Error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A leadás helyének megadása kötelezõ..
        /// </summary>
        public static string Error_place_of_delivery {
            get {
                return ResourceManager.GetString("Error_place_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az átvétel helyének megadása kötelezõ..
        /// </summary>
        public static string Error_place_of_receipt {
            get {
                return ResourceManager.GetString("Error_place_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az utazás célját kötelező megadni!.
        /// </summary>
        public static string Error_purpose_of_the_trip {
            get {
                return ResourceManager.GetString("Error_purpose_of_the_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdeti dátumot kötelező megadni!.
        /// </summary>
        public static string Error_starting_date {
            get {
                return ResourceManager.GetString("Error_starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő helyet kötelező megadni!.
        /// </summary>
        public static string Error_starting_place {
            get {
                return ResourceManager.GetString("Error_starting_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megbízás azonosítót kötelező megadni..
        /// </summary>
        public static string Error_task_id {
            get {
                return ResourceManager.GetString("Error_task_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A leadás idejének megadása kötelezõ..
        /// </summary>
        public static string Error_time_of_delivery {
            get {
                return ResourceManager.GetString("Error_time_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az átvétel idejének megadása kötelezõ..
        /// </summary>
        public static string Error_time_of_receipt {
            get {
                return ResourceManager.GetString("Error_time_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kiadás típusának megadása kötelező..
        /// </summary>
        public static string Error_type {
            get {
                return ResourceManager.GetString("Error_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az azonosító megadása kötelező!.
        /// </summary>
        public static string Error_type_id {
            get {
                return ResourceManager.GetString("Error_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév megadása kötelezõ..
        /// </summary>
        public static string Error_username {
            get {
                return ResourceManager.GetString("Error_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rendszám megadása kötelező!.
        /// </summary>
        public static string Error_vehicle_registration_number {
            get {
                return ResourceManager.GetString("Error_vehicle_registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raktár címét meg kell adnod!.
        /// </summary>
        public static string Error_Warehouse_address {
            get {
                return ResourceManager.GetString("Error_Warehouse_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raktár tulajdonosát meg kell adnod!.
        /// </summary>
        public static string Error_Warehouse_owner {
            get {
                return ResourceManager.GetString("Error_Warehouse_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A súlyt kötelező megadni!.
        /// </summary>
        public static string Error_weight {
            get {
                return ResourceManager.GetString("Error_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havi kiadások.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás azonosító.
        /// </summary>
        public static string Expenses_id {
            get {
                return ResourceManager.GetString("Expenses_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végleges összeg.
        /// </summary>
        public static string Final_Payment {
            get {
                return ResourceManager.GetString("Final_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénzügy.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzemanyag.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes név.
        /// </summary>
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen bejelentkeztél.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Home_title {
            get {
                return ResourceManager.GetString("Home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány ID.
        /// </summary>
        public static string Id_cargo {
            get {
                return ResourceManager.GetString("Id_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilkép.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilkép megváltoztatása.
        /// </summary>
        public static string Image_change {
            get {
                return ResourceManager.GetString("Image_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználó már létezik!.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terhelés max súlya.
        /// </summary>
        public static string Max_weight {
            get {
                return ResourceManager.GetString("Max_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új adat.
        /// </summary>
        public static string New_data {
            get {
                return ResourceManager.GetString("New_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új felhasználó.
        /// </summary>
        public static string New_user {
            get {
                return ResourceManager.GetString("New_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl nem található!.
        /// </summary>
        public static string No_excel {
            get {
                return ResourceManager.GetString("No_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csak .xlsx formátum elfogadott!.
        /// </summary>
        public static string Not_excel {
            get {
                return ResourceManager.GetString("Not_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Notfound {
            get {
                return ResourceManager.GetString("Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb megállóhelyek.
        /// </summary>
        public static string Other_stops {
            get {
                return ResourceManager.GetString("Other_stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenlegi jelszó.
        /// </summary>
        public static string Password_current {
            get {
                return ResourceManager.GetString("Password_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helytelen jelszó..
        /// </summary>
        public static string Password_error {
            get {
                return ResourceManager.GetString("Password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó újra.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszavak nem egyeznek!.
        /// </summary>
        public static string PasswordConfirm_error {
            get {
                return ResourceManager.GetString("PasswordConfirm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igért összeg.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büntetés összege.
        /// </summary>
        public static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büntetés.
        /// </summary>
        public static string Penalty_expenses {
            get {
                return ResourceManager.GetString("Penalty_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        public static string Phone_number {
            get {
                return ResourceManager.GetString("Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadás helye.
        /// </summary>
        public static string Place_of_delivery {
            get {
                return ResourceManager.GetString("Place_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átvétel helye.
        /// </summary>
        public static string Place_of_receipt {
            get {
                return ResourceManager.GetString("Place_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek jelentkezz be!.
        /// </summary>
        public static string Please_Login {
            get {
                return ResourceManager.GetString("Please_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabályzat.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az alkalmazás egyetemi szakdolgozat céljából készül! így minden ehhez kapcsolódó szabály érvényes rá..
        /// </summary>
        public static string Privacy_text {
            get {
                return ResourceManager.GetString("Privacy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az alkalmazás a fejlesztés során valós adatokat nem tartalmaz..
        /// </summary>
        public static string Privacy_text2 {
            get {
                return ResourceManager.GetString("Privacy_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az út célja.
        /// </summary>
        public static string Purpose_of_the_trip {
            get {
                return ResourceManager.GetString("Purpose_of_the_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlékezz rám.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javítás.
        /// </summary>
        public static string Repair_cost {
            get {
                return ResourceManager.GetString("Repair_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás a javításról.
        /// </summary>
        public static string Repair_description {
            get {
                return ResourceManager.GetString("Repair_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útdíjak.
        /// </summary>
        public static string Road_fees {
            get {
                return ResourceManager.GetString("Road_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Út azonosító.
        /// </summary>
        public static string Road_id {
            get {
                return ResourceManager.GetString("Road_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utak.
        /// </summary>
        public static string Roads {
            get {
                return ResourceManager.GetString("Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogosultság.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés....
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár szekció.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válaszd ki....
        /// </summary>
        public static string Select_placeholder {
            get {
                return ResourceManager.GetString("Select_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szállítási követelmények.
        /// </summary>
        public static string Shipping_requirements {
            get {
                return ResourceManager.GetString("Shipping_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő dátum.
        /// </summary>
        public static string Starting_date {
            get {
                return ResourceManager.GetString("Starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő hely.
        /// </summary>
        public static string Starting_place {
            get {
                return ResourceManager.GetString("Starting_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás kezdete.
        /// </summary>
        public static string Storage_starting_time {
            get {
                return ResourceManager.GetString("Storage_starting_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás ideje.
        /// </summary>
        public static string Storage_time {
            get {
                return ResourceManager.GetString("Storage_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktáros.
        /// </summary>
        public static string Storageman {
            get {
                return ResourceManager.GetString("Storageman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás azonosító.
        /// </summary>
        public static string Task_id {
            get {
                return ResourceManager.GetString("Task_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízások.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízások.
        /// </summary>
        public static string Tasks_title {
            get {
                return ResourceManager.GetString("Tasks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Késés.
        /// </summary>
        public static string Time_of_delay {
            get {
                return ResourceManager.GetString("Time_of_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadás ideje.
        /// </summary>
        public static string Time_of_delivery {
            get {
                return ResourceManager.GetString("Time_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átvétel ideje.
        /// </summary>
        public static string Time_of_receipt {
            get {
                return ResourceManager.GetString("Time_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók létrehozása.
        /// </summary>
        public static string Title_create_user {
            get {
                return ResourceManager.GetString("Title_create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Title_login {
            get {
                return ResourceManager.GetString("Title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók törlése.
        /// </summary>
        public static string Title_user_delete {
            get {
                return ResourceManager.GetString("Title_user_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók módosítása.
        /// </summary>
        public static string Title_user_edit {
            get {
                return ResourceManager.GetString("Title_user_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Járművek.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Típus.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Típus azonosító.
        /// </summary>
        public static string Type_id {
            get {
                return ResourceManager.GetString("Type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó azonosító.
        /// </summary>
        public static string User_id {
            get {
                return ResourceManager.GetString("User_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jármû Rendszáma.
        /// </summary>
        public static string Vehicle_registration_number {
            get {
                return ResourceManager.GetString("Vehicle_registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár címe.
        /// </summary>
        public static string Warehouse_address {
            get {
                return ResourceManager.GetString("Warehouse_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár azonosító.
        /// </summary>
        public static string Warehouse_id {
            get {
                return ResourceManager.GetString("Warehouse_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonos.
        /// </summary>
        public static string Warehouse_owner {
            get {
                return ResourceManager.GetString("Warehouse_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktáros.
        /// </summary>
        public static string Warehouseman {
            get {
                return ResourceManager.GetString("Warehouseman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súly.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
