//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargotruck.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cargotruck.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Január.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Október.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Február.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Március.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Április.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Május.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Június.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Július.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augusztus.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szeptember.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Könyvelő.
        /// </summary>
        public static string Accountant {
            get {
                return ResourceManager.GetString("Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabály hozzáadása.
        /// </summary>
        public static string Add_privacy {
            get {
                return ResourceManager.GetString("Add_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor felület.
        /// </summary>
        public static string Admin_page {
            get {
                return ResourceManager.GetString("Admin_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor felület.
        /// </summary>
        public static string Admin_title {
            get {
                return ResourceManager.GetString("Admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rossz felhasználónév vagy jelszó..
        /// </summary>
        public static string Bad_username {
            get {
                return ResourceManager.GetString("Bad_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autómárka.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány.
        /// </summary>
        public static string cargo {
            get {
                return ResourceManager.GetString("cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány azonosító.
        /// </summary>
        public static string Cargo_id {
            get {
                return ResourceManager.GetString("Cargo_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakományos.
        /// </summary>
        public static string Cargo_man {
            get {
                return ResourceManager.GetString("Cargo_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakományok.
        /// </summary>
        public static string Cargoes {
            get {
                return ResourceManager.GetString("Cargoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rakomány vár kiszállításra.
        /// </summary>
        public static string Cargoes_unfinished {
            get {
                return ResourceManager.GetString("Cargoes_unfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megváltoztatása.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kiadások értékeinek ellenőrzése nem sikerült!.
        /// </summary>
        public static string CheckFailed {
            get {
                return ResourceManager.GetString("CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljesítve.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljesítés ideje.
        /// </summary>
        public static string Completion_time {
            get {
                return ResourceManager.GetString("Completion_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás költsége.
        /// </summary>
        public static string Cost_of_storage {
            get {
                return ResourceManager.GetString("Cost_of_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány adatok  létrehozása.
        /// </summary>
        public static string Create_cargo {
            get {
                return ResourceManager.GetString("Create_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadások  létrehozása.
        /// </summary>
        public static string Create_expense {
            get {
                return ResourceManager.GetString("Create_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havi kiadás hozzáadása.
        /// </summary>
        public static string Create_monthly_expense {
            get {
                return ResourceManager.GetString("Create_monthly_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új fiók.
        /// </summary>
        public static string Create_new {
            get {
                return ResourceManager.GetString("Create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Út adatok  létrehozása.
        /// </summary>
        public static string Create_road {
            get {
                return ResourceManager.GetString("Create_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás létrehozása.
        /// </summary>
        public static string Create_task {
            get {
                return ResourceManager.GetString("Create_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jármű adatainak  létrehozása.
        /// </summary>
        public static string Create_truck {
            get {
                return ResourceManager.GetString("Create_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár adatok létrehozása.
        /// </summary>
        public static string Create_warehouse {
            get {
                return ResourceManager.GetString("Create_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letöltés CSV-ként.
        /// </summary>
        public static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfogyott a napi valutaváltás lekérésének a száma a hónapban. .
        /// </summary>
        public static string currency_api_is_exceeded {
            get {
                return ResourceManager.GetString("currency_api_is_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta váltás lekérésének ideje (mp).
        /// </summary>
        public static string CurrencyExchangeWaitTime {
            get {
                return ResourceManager.GetString("CurrencyExchangeWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok feltöltése.
        /// </summary>
        public static string Data_import {
            get {
                return ResourceManager.GetString("Data_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az időpontok közötti adatok megjelenítve..
        /// </summary>
        public static string date_filter_info {
            get {
                return ResourceManager.GetString("date-filter-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni szeretnéd?.
        /// </summary>
        public static string Delete_ {
            get {
                return ResourceManager.GetString("Delete?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás törlése.
        /// </summary>
        public static string Delete_tasks {
            get {
                return ResourceManager.GetString("Delete_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szállít.
        /// </summary>
        public static string delivering {
            get {
                return ResourceManager.GetString("delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szállítás követelményei.
        /// </summary>
        public static string Delivery_requirements {
            get {
                return ResourceManager.GetString("Delivery_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült előállítani a fájlt!.
        /// </summary>
        public static string Document_failder_to_create {
            get {
                return ResourceManager.GetString("Document_failder_to_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr fizetése.
        /// </summary>
        public static string Driver_salary {
            get {
                return ResourceManager.GetString("Driver_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofőr költése.
        /// </summary>
        public static string Driver_spending {
            get {
                return ResourceManager.GetString("Driver_spending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kereset.
        /// </summary>
        public static string Earning {
            get {
                return ResourceManager.GetString("Earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosít.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány adatok szerkesztése.
        /// </summary>
        public static string Edit_cargo {
            get {
                return ResourceManager.GetString("Edit_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadások szerkesztése.
        /// </summary>
        public static string Edit_expense {
            get {
                return ResourceManager.GetString("Edit_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havi kiadások szerkesztése.
        /// </summary>
        public static string Edit_monthly_expense {
            get {
                return ResourceManager.GetString("Edit_monthly_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil szerkesztése.
        /// </summary>
        public static string Edit_profile {
            get {
                return ResourceManager.GetString("Edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Út szerkesztése.
        /// </summary>
        public static string Edit_road {
            get {
                return ResourceManager.GetString("Edit_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás módosítása.
        /// </summary>
        public static string Edit_task {
            get {
                return ResourceManager.GetString("Edit_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jármű adatainak szerkesztése.
        /// </summary>
        public static string Edit_truck {
            get {
                return ResourceManager.GetString("Edit_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár adatok szerkesztése.
        /// </summary>
        public static string Edit_warehouse {
            get {
                return ResourceManager.GetString("Edit_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres excel fájl!.
        /// </summary>
        public static string Empty_excel {
            get {
                return ResourceManager.GetString("Empty_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angol.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befejezés dátum.
        /// </summary>
        public static string Ending_date {
            get {
                return ResourceManager.GetString("Ending_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befejezés helye.
        /// </summary>
        public static string Ending_place {
            get {
                return ResourceManager.GetString("Ending_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az autómárka megadása kötelező!.
        /// </summary>
        public static string Error_brand {
            get {
                return ResourceManager.GetString("Error_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az irány megadása kötelező.
        /// </summary>
        public static string Error_direction {
            get {
                return ResourceManager.GetString("Error_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail megadása kötelezõ..
        /// </summary>
        public static string Error_email {
            get {
                return ResourceManager.GetString("Error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név megadása kötelezõ..
        /// </summary>
        public static string Error_full_name {
            get {
                return ResourceManager.GetString("Error_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jármű teherbírását kötelező megadni!.
        /// </summary>
        public static string Error_max_weight {
            get {
                return ResourceManager.GetString("Error_max_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt, kérlek próbáld meg később..
        /// </summary>
        public static string Error_page_text {
            get {
                return ResourceManager.GetString("Error_page_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner megadása kötelezõ..
        /// </summary>
        public static string Error_partner {
            get {
                return ResourceManager.GetString("Error_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megadása kötelezõ..
        /// </summary>
        public static string Error_password {
            get {
                return ResourceManager.GetString("Error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak 8 és 30 karakter között kell lennie!.
        /// </summary>
        public static string Error_password_lenght {
            get {
                return ResourceManager.GetString("Error_password_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell kis- és nagybetűt, számot és speciális karaktert!.
        /// </summary>
        public static string Error_password_validation {
            get {
                return ResourceManager.GetString("Error_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A leadás helyének megadása kötelezõ..
        /// </summary>
        public static string Error_place_of_delivery {
            get {
                return ResourceManager.GetString("Error_place_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az átvétel helyének megadása kötelezõ..
        /// </summary>
        public static string Error_place_of_receipt {
            get {
                return ResourceManager.GetString("Error_place_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az utazás célját kötelező megadni!.
        /// </summary>
        public static string Error_purpose_of_the_trip {
            get {
                return ResourceManager.GetString("Error_purpose_of_the_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beállítás értékének megadása kötelező!.
        /// </summary>
        public static string Error_setting_value {
            get {
                return ResourceManager.GetString("Error_setting_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdeti dátumot kötelező megadni!.
        /// </summary>
        public static string Error_starting_date {
            get {
                return ResourceManager.GetString("Error_starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő helyet kötelező megadni!.
        /// </summary>
        public static string Error_starting_place {
            get {
                return ResourceManager.GetString("Error_starting_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megbízás azonosítót kötelező megadni..
        /// </summary>
        public static string Error_task_id {
            get {
                return ResourceManager.GetString("Error_task_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A leadás idejének megadása kötelezõ..
        /// </summary>
        public static string Error_time_of_delivery {
            get {
                return ResourceManager.GetString("Error_time_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az átvétel idejének megadása kötelezõ..
        /// </summary>
        public static string Error_time_of_receipt {
            get {
                return ResourceManager.GetString("Error_time_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kiadás típusának megadása kötelező..
        /// </summary>
        public static string Error_type {
            get {
                return ResourceManager.GetString("Error_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az azonosító megadása kötelező!.
        /// </summary>
        public static string Error_type_id {
            get {
                return ResourceManager.GetString("Error_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév megadása kötelezõ..
        /// </summary>
        public static string Error_username {
            get {
                return ResourceManager.GetString("Error_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rendszám megadása kötelező!.
        /// </summary>
        public static string Error_vehicle_registration_number {
            get {
                return ResourceManager.GetString("Error_vehicle_registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raktár címét meg kell adnod!.
        /// </summary>
        public static string Error_Warehouse_address {
            get {
                return ResourceManager.GetString("Error_Warehouse_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raktár tulajdonosát meg kell adnod!.
        /// </summary>
        public static string Error_Warehouse_owner {
            get {
                return ResourceManager.GetString("Error_Warehouse_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A súlyt kötelező megadni!.
        /// </summary>
        public static string Error_weight {
            get {
                return ResourceManager.GetString("Error_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letöltés Excel-ként.
        /// </summary>
        public static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás azonosító.
        /// </summary>
        public static string Expense_id {
            get {
                return ResourceManager.GetString("Expense_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás azonosító.
        /// </summary>
        public static string Expense_id_ {
            get {
                return ResourceManager.GetString("Expense_id:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadások.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás azonosító.
        /// </summary>
        public static string Expenses_id {
            get {
                return ResourceManager.GetString("Expenses_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénzügyek.
        /// </summary>
        public static string Expenses_menu {
            get {
                return ResourceManager.GetString("Expenses_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok letöltése.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok feltöltése.
        /// </summary>
        public static string File_input {
            get {
                return ResourceManager.GetString("File_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szűrés.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végleges összeg.
        /// </summary>
        public static string Final_Payment {
            get {
                return ResourceManager.GetString("Final_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénzügy.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visszaút.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darab felhasználó létezik..
        /// </summary>
        public static string From_user {
            get {
                return ResourceManager.GetString("From_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzemanyag.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljes név.
        /// </summary>
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garázsban.
        /// </summary>
        public static string garage {
            get {
                return ResourceManager.GetString("garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generált adat.
        /// </summary>
        public static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány az adminisztrátor felület →.
        /// </summary>
        public static string go_to_admin {
            get {
                return ResourceManager.GetString("go_to_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány a rakományok oldal →.
        /// </summary>
        public static string go_to_cargoes {
            get {
                return ResourceManager.GetString("go_to_cargoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány a kiadások oldal →.
        /// </summary>
        public static string go_to_expenses {
            get {
                return ResourceManager.GetString("go_to_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány a havi kiadások oldal →.
        /// </summary>
        public static string go_to_monthly_expenses {
            get {
                return ResourceManager.GetString("go_to_monthly_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány az utak oldal →.
        /// </summary>
        public static string go_to_roads {
            get {
                return ResourceManager.GetString("go_to_roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány a megbízások oldal →.
        /// </summary>
        public static string go_to_tasks {
            get {
                return ResourceManager.GetString("go_to_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány az járművek oldal →.
        /// </summary>
        public static string go_to_trucks {
            get {
                return ResourceManager.GetString("go_to_trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irány az raktárak oldal →.
        /// </summary>
        public static string go_to_warehouses {
            get {
                return ResourceManager.GetString("go_to_warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen bejelentkeztél.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Home_title {
            get {
                return ResourceManager.GetString("Home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        public static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakomány azonosító.
        /// </summary>
        public static string Id_cargo {
            get {
                return ResourceManager.GetString("Id_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilkép.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilkép megváltoztatása.
        /// </summary>
        public static string Image_change {
            get {
                return ResourceManager.GetString("Image_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltöltés Excel-ből.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktárban.
        /// </summary>
        public static string InWarehouse {
            get {
                return ResourceManager.GetString("InWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelv.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betöltés....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kölcsönadva.
        /// </summary>
        public static string loaned {
            get {
                return ResourceManager.GetString("loaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználó már létezik!.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bejelentkezés.
        /// </summary>
        public static string logins {
            get {
                return ResourceManager.GetString("logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to különbőző felhasználó.
        /// </summary>
        public static string Logins_same {
            get {
                return ResourceManager.GetString("Logins_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötelezően választani kell!.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terhelés max súlya.
        /// </summary>
        public static string Max_weight {
            get {
                return ResourceManager.GetString("Max_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincsenek adatsorok a fájlban!.
        /// </summary>
        public static string Missing_data_rows {
            get {
                return ResourceManager.GetString("Missing_data_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hónap.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havi kiadások.
        /// </summary>
        public static string Monthly_expenses {
            get {
                return ResourceManager.GetString("Monthly_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új adat.
        /// </summary>
        public static string New_data {
            get {
                return ResourceManager.GetString("New_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új felhasználó.
        /// </summary>
        public static string New_user {
            get {
                return ResourceManager.GetString("New_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új felhasználó létrehozása.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs adat!.
        /// </summary>
        public static string No_content {
            get {
                return ResourceManager.GetString("No_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl nem található!.
        /// </summary>
        public static string No_excel {
            get {
                return ResourceManager.GetString("No_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem található adat!.
        /// </summary>
        public static string No_records {
            get {
                return ResourceManager.GetString("No_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs teljesítve.
        /// </summary>
        public static string Not_completed {
            get {
                return ResourceManager.GetString("Not_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csak .xlsx formátum elfogadott!.
        /// </summary>
        public static string Not_excel {
            get {
                return ResourceManager.GetString("Not_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználó nem található..
        /// </summary>
        public static string Not_found {
            get {
                return ResourceManager.GetString("Not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó által létrehozott.
        /// </summary>
        public static string Not_generated {
            get {
                return ResourceManager.GetString("Not_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem egyeznek az oszlopok!.
        /// </summary>
        public static string Not_match_col {
            get {
                return ResourceManager.GetString("Not_match_col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzó oszlopok az adattáblában!.
        /// </summary>
        public static string Not_match_col_count {
            get {
                return ResourceManager.GetString("Not_match_col_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feltöltése nem sikerült..
        /// </summary>
        public static string Not_uploaded {
            get {
                return ResourceManager.GetString("Not_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem található!.
        /// </summary>
        public static string Notfound {
            get {
                return ResourceManager.GetString("Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs kiválasztva.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs raktárban.
        /// </summary>
        public static string NotInWarehouse {
            get {
                return ResourceManager.GetString("NotInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úton.
        /// </summary>
        public static string on_road {
            get {
                return ResourceManager.GetString("on_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem lehet negatív szám!.
        /// </summary>
        public static string OnlyPositive {
            get {
                return ResourceManager.GetString("OnlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb megállóhelyek.
        /// </summary>
        public static string other_stops {
            get {
                return ResourceManager.GetString("other_stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonos.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorok száma.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenlegi jelszó.
        /// </summary>
        public static string Password_current {
            get {
                return ResourceManager.GetString("Password_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helytelen jelszó..
        /// </summary>
        public static string Password_error {
            get {
                return ResourceManager.GetString("Password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó újra.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszavak nem egyeznek!.
        /// </summary>
        public static string PasswordConfirm_error {
            get {
                return ResourceManager.GetString("PasswordConfirm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igért összeg.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letöltés pdf-ként.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büntetés összege.
        /// </summary>
        public static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büntetés.
        /// </summary>
        public static string Penalty_expenses {
            get {
                return ResourceManager.GetString("Penalty_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        public static string Phone_number {
            get {
                return ResourceManager.GetString("Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadás helye.
        /// </summary>
        public static string Place_of_delivery {
            get {
                return ResourceManager.GetString("Place_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átvétel helye.
        /// </summary>
        public static string Place_of_receipt {
            get {
                return ResourceManager.GetString("Place_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek jelentkezz be!.
        /// </summary>
        public static string Please_Login {
            get {
                return ResourceManager.GetString("Please_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabályzat.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabály elnevezése.
        /// </summary>
        public static string Privacy_name {
            get {
                return ResourceManager.GetString("Privacy_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabály szövege.
        /// </summary>
        public static string Privacy_text {
            get {
                return ResourceManager.GetString("Privacy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az út célja.
        /// </summary>
        public static string Purpose_of_the_trip {
            get {
                return ResourceManager.GetString("Purpose_of_the_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlékezz rám.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bérelve.
        /// </summary>
        public static string rented {
            get {
                return ResourceManager.GetString("rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javítás.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javítás költsége.
        /// </summary>
        public static string Repair_cost {
            get {
                return ResourceManager.GetString("Repair_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás a javításról.
        /// </summary>
        public static string Repair_description {
            get {
                return ResourceManager.GetString("Repair_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to út.
        /// </summary>
        public static string road {
            get {
                return ResourceManager.GetString("road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útdíjak.
        /// </summary>
        public static string Road_fees {
            get {
                return ResourceManager.GetString("Road_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Út azonosító.
        /// </summary>
        public static string Road_id {
            get {
                return ResourceManager.GetString("Road_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utak.
        /// </summary>
        public static string Roads {
            get {
                return ResourceManager.GetString("Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogosultság.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár szekció.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válaszd ki....
        /// </summary>
        public static string Select_placeholder {
            get {
                return ResourceManager.GetString("Select_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szállítási követelmények.
        /// </summary>
        public static string Shipping_requirements {
            get {
                return ResourceManager.GetString("Shipping_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő dátum.
        /// </summary>
        public static string Starting_date {
            get {
                return ResourceManager.GetString("Starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő hely.
        /// </summary>
        public static string Starting_place {
            get {
                return ResourceManager.GetString("Starting_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás.
        /// </summary>
        public static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás kezdete.
        /// </summary>
        public static string Storage_starting_time {
            get {
                return ResourceManager.GetString("Storage_starting_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktározás ideje.
        /// </summary>
        public static string Storage_time {
            get {
                return ResourceManager.GetString("Storage_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktáros.
        /// </summary>
        public static string Storageman {
            get {
                return ResourceManager.GetString("Storageman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen frissítve!.
        /// </summary>
        public static string Succesfull_update {
            get {
                return ResourceManager.GetString("Succesfull_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltöltés sikeres!.
        /// </summary>
        public static string Success_upload {
            get {
                return ResourceManager.GetString("Success_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízás azonosító.
        /// </summary>
        public static string Task_id {
            get {
                return ResourceManager.GetString("Task_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízások.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megbízások.
        /// </summary>
        public static string Tasks_title {
            get {
                return ResourceManager.GetString("Tasks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megbízás vár befejezésre.
        /// </summary>
        public static string Tasks_unfinished {
            get {
                return ResourceManager.GetString("Tasks_unfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Késés.
        /// </summary>
        public static string Time_of_delay {
            get {
                return ResourceManager.GetString("Time_of_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadás ideje.
        /// </summary>
        public static string Time_of_delivery {
            get {
                return ResourceManager.GetString("Time_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átvétel ideje.
        /// </summary>
        public static string Time_of_receipt {
            get {
                return ResourceManager.GetString("Time_of_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók létrehozása.
        /// </summary>
        public static string Title_create_user {
            get {
                return ResourceManager.GetString("Title_create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Title_login {
            get {
                return ResourceManager.GetString("Title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók törlése.
        /// </summary>
        public static string Title_user_delete {
            get {
                return ResourceManager.GetString("Title_user_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiók módosítása.
        /// </summary>
        public static string Title_user_edit {
            get {
                return ResourceManager.GetString("Title_user_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaút.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jármű.
        /// </summary>
        public static string truck {
            get {
                return ResourceManager.GetString("truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Járművek.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jármű van használatban.
        /// </summary>
        public static string Trucks_unfinished {
            get {
                return ResourceManager.GetString("Trucks_unfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letöltés szöveg dokumentumként.
        /// </summary>
        public static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Típus.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Típus azonosító.
        /// </summary>
        public static string Type_id {
            get {
                return ResourceManager.GetString("Type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javítás alatt.
        /// </summary>
        public static string under_repair {
            get {
                return ResourceManager.GetString("under_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó azonosító.
        /// </summary>
        public static string User_id {
            get {
                return ResourceManager.GetString("User_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jármű rendszáma.
        /// </summary>
        public static string Vehicle_registration_number {
            get {
                return ResourceManager.GetString("Vehicle_registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár címe.
        /// </summary>
        public static string Warehouse_address {
            get {
                return ResourceManager.GetString("Warehouse_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár azonosító.
        /// </summary>
        public static string Warehouse_id {
            get {
                return ResourceManager.GetString("Warehouse_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonos.
        /// </summary>
        public static string Warehouse_owner {
            get {
                return ResourceManager.GetString("Warehouse_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár részleg.
        /// </summary>
        public static string Warehouse_section {
            get {
                return ResourceManager.GetString("Warehouse_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktáros.
        /// </summary>
        public static string Warehouseman {
            get {
                return ResourceManager.GetString("Warehouseman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súly.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Év.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
